# Reconciliation Configuration
google_credentials = "auth/credentials.json"


system_prompt = """The input name and match list are school names, districts, etc.
Wherein SD = school district"""

model_name = "gpt-4"

include_references = true

include_input = true

[input_sheet]
url = "https://docs.google.com/spreadsheets/d/1ck-oLq0ZZcJ5bE25iCniKEbpRH6W8hqOYIGp_0yPk7I/edit?gid=2061681244#gid=2061681244"
range_name = "Internet"
column_name = "Customer"

[[reference_sheets]]
url = "https://docs.google.com/spreadsheets/d/1qAsS6js10tyj_bazOg8Ee-4Uv3WtXooL3UQzibyNMeQ/edit?gid=1488438780#gid=1488438780"
range_name = "LEA Summary"
column_name = "LEA Name"

# Add additional reference sheets as needed
# [[reference_sheets]]
# url = "..."
# range_name = "..."
# column_name = "..."

[output_sheet]
url = "https://docs.google.com/spreadsheets/d/1ck-oLq0ZZcJ5bE25iCniKEbpRH6W8hqOYIGp_0yPk7I/edit?gid=2131558729#gid=2131558729"
range_name = "Matched"
column_name = "Name"
